import { StyleSheet } from 'react-native';
import { Colors, Radius, Shadows, Spacing, Typography } from '@/constants/theme';

export const profileStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.background },
  safeTop: { backgroundColor: Colors.darkDeep },
  scroll: { paddingBottom: 120 },
  headerBg: {
    backgroundColor: Colors.darkDeep,
    borderBottomLeftRadius: 48,
    borderBottomRightRadius: 48,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 25 },
    shadowOpacity: 0.25,
    shadowRadius: 50,
    elevation: 8,
  },
  riderHeader: { paddingBottom: 128 },
  driverHeader: { justifyContent: 'flex-start' },
  riderOrbCyan: {
    position: 'absolute',
    top: -128,
    left: -128,
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: 'rgba(2,132,199,0.2)',
  },
  riderOrbPink: {
    position: 'absolute',
    bottom: -128,
    right: -128,
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: 'rgba(192,38,211,0.1)',
  },
  driverOrbIndigo: {
    position: 'absolute',
    top: -128,
    right: -128,
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: 'rgba(79,70,229,0.2)',
  },
  driverOrbPurple: {
    position: 'absolute',
    bottom: -128,
    left: -128,
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: 'rgba(147,51,234,0.1)',
  },
  profileCardWrap: {
    marginHorizontal: Spacing.xl,
    marginTop: -72,
    borderRadius: Radius.xl,
    overflow: 'visible',
    zIndex: 2,
  },
  profileCardBlur: {
    borderRadius: Radius.xl,
    overflow: 'visible',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.6)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.08,
    shadowRadius: 40,
    elevation: 8,
  },
  profileCardInner: {
    paddingTop: 64.8,
    paddingHorizontal: 24.8,
    paddingBottom: 24.8,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: Radius.xl,
    overflow: 'visible',
    minHeight: 237,
  },
  profileCardAndroid: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.6)',
    ...Shadows.card,
  },
  name: {
    fontFamily: Typography.fonts.black,
    fontSize: Typography.fontSizes.xl,
    color: Colors.textPrimary,
    letterSpacing: -0.6,
    lineHeight: 32,
    marginBottom: 4,
    textAlign: 'center',
  },
  email: {
    fontFamily: Typography.fonts.medium,
    fontSize: Typography.fontSizes.sm,
    color: Colors.textMuted,
    letterSpacing: -0.3,
    marginBottom: Spacing.xl,
    lineHeight: 16,
    textAlign: 'center',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: Spacing.xl,
    justifyContent: 'center',
  },
  captainPill: {
    backgroundColor: Colors.surfaceIndigo,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: Radius.full,
  },
  captainText: {
    fontFamily: Typography.fonts.bold,
    fontSize: Typography.fontSizes.sm,
    color: Colors.primary,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    lineHeight: 16,
  },
  dot: {
    fontFamily: Typography.fonts.regular,
    fontSize: 15,
    color: '#CBD5E1',
    lineHeight: 22.5,
  },
  vehicle: {
    fontFamily: Typography.fonts.bold,
    fontSize: Typography.fontSizes.sm,
    color: Colors.textSecondary,
    letterSpacing: -0.3,
    lineHeight: 16,
  },
  bannerWrap: { marginHorizontal: Spacing.xl, marginTop: 24 },
  premiumBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: Radius.card,
    padding: Spacing.xl,
    gap: Spacing.base,
    minHeight: 96,
    overflow: 'hidden',
    shadowColor: '#BAE6FD',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 6,
  },
  levelBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: Radius.card,
    padding: Spacing.xl,
    gap: Spacing.base,
    minHeight: 96,
    overflow: 'hidden',
    shadowColor: '#C7D2FE',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 15,
    elevation: 6,
  },
  bannerOrb: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 128,
    height: 128,
    borderRadius: 64,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  bannerIcon: {
    width: 48,
    height: 48,
    borderRadius: Radius.lg,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerText: { flex: 1 },
  premiumTitle: {
    fontFamily: Typography.fonts.black,
    fontSize: 18,
    color: Colors.textPrimary,
    letterSpacing: -0.45,
    lineHeight: 28,
  },
  premiumSub: {
    fontFamily: Typography.fonts.medium,
    fontSize: Typography.fontSizes.sm,
    color: '#E0F2FE',
    letterSpacing: -0.3,
    lineHeight: 16,
  },
  levelTitle: {
    fontFamily: Typography.fonts.black,
    fontSize: 18,
    color: Colors.textPrimary,
    letterSpacing: -0.45,
    lineHeight: 28,
  },
  levelSub: {
    fontFamily: Typography.fonts.medium,
    fontSize: Typography.fontSizes.sm,
    color: '#E0E7FF',
    letterSpacing: -0.3,
    lineHeight: 16,
  },
  sectionLabel: {
    fontFamily: Typography.fonts.black,
    fontSize: Typography.fontSizes.sm,
    color: Colors.textMuted,
    letterSpacing: 2.4,
    textTransform: 'uppercase',
    marginHorizontal: Spacing.xl,
    marginTop: 24,
    marginBottom: Spacing.md,
    paddingLeft: Spacing.sm,
  },
});
